#!/bin/sh

export PYTHON="python3"
export VENV="_python"
export PATH="$PWD/$VENV/bin:$PATH"
export PREFIX="./_site"
export PAGES_ORIGIN="origin/gh-pages"
export PAGES_LOCAL="gh-pages"

venv_setup() {
    if [ ! -d "$VENV" ]; then
        $PYTHON -m venv "$VENV"
    fi
    $PYTHON -m pip install -U -r requirements.txt
}

if [ ! -d "$VENV" ] && [ "_$1" != "_venv" ]; then
    echo "Setting up the virtual environment: $VENV"
    venv_setup
fi

case $1 in
    venv)
        case $2 in
            update) venv_setup ;;
            remove) rm -r "$VENV" ;;
            *) echo "Usage: $0 $1 update|remove" ;;
        esac ;;
    pages)
        case $2 in
            checkout)
                if [ -e "$PREFIX" ]; then
                    if [ "_$3" != '_force' ]; then
                        echo -n "Press Enter to delete $PREFIX or Ctrl+C to abort"
                        read a
                    fi
                    rm -rf "$PREFIX"
                fi
                git worktree prune
                git worktree add "$PREFIX" "$PAGES_ORIGIN" ;;
            diff)
                (
                    cd "$PREFIX"
                    git diff
                ) ;;
            commit)
                (
                    cd "$PREFIX"
                    git branch -D "$PAGES_LOCAL" || true
                    git checkout -b "$PAGES_LOCAL"
                    git branch --set-upstream-to="$PAGES_ORIGIN" "$PAGES_LOCAL"
                    git add .
                    git commit -m "Jenkins: Обновление статичных файлов" || true
                ) ;;
            push)
                (
                    cd "$PREFIX"
                    git push origin "$PAGES_LOCAL"
                ) ;;
            *) echo "Usage: $0 $1 checkout|diff|commit|push" ;;
        esac ;;
    build) $PYTHON -m templates.utils.generate ;;
    serve) $PYTHON -m templates.utils.serve ;;
    download-chats) $PYTHON -m templates.utils.chats ;;
    sh) $@ ;;
    cli) $PYTHON -i -m templates.utils.cli ;;
    python) shift; $PYTHON $@ ;;
    *) echo "Usage: $0 venv|build|serve|download-chats|sh|cli|python" ;;
esac
